// <auto-generated />
using System;
using DataAccessLayer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260619163101_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccessLayer.Entities.AiModel", b =>
                {
                    b.Property<int>("AiModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AiModelId"));

                    b.Property<string>("ApiEndpoint")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<int>("MaxTokens")
                        .HasColumnType("int");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Temperature")
                        .HasColumnType("float");

                    b.HasKey("AiModelId");

                    b.ToTable("AiModels");

                    b.HasData(
                        new
                        {
                            AiModelId = 1,
                            ApiEndpoint = "https://generativelanguage.googleapis.com/v1beta",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Google Gemini 2.0 Flash — fast & cost-effective",
                            IsActive = true,
                            IsDefault = true,
                            MaxTokens = 8192,
                            ModelName = "gemini-2.0-flash",
                            Provider = "Gemini",
                            Temperature = 0.69999999999999996
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Entities.BenchmarkResult", b =>
                {
                    b.Property<int>("BenchmarkResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BenchmarkResultId"));

                    b.Property<decimal?>("AnswerSimilarityScore")
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal?>("ContextRecallScore")
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExperimentId")
                        .HasColumnType("int");

                    b.Property<decimal?>("FaithfulnessScore")
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("GeneratedAnswer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LatencyMs")
                        .HasColumnType("int");

                    b.Property<decimal?>("RelevanceScore")
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("RetrievedChunkIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TestSetId")
                        .HasColumnType("int");

                    b.HasKey("BenchmarkResultId");

                    b.HasIndex("ExperimentId");

                    b.HasIndex("TestSetId");

                    b.ToTable("BenchmarkResults");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Chapter", b =>
                {
                    b.Property<int>("ChapterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChapterId"));

                    b.Property<string>("ChapterName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("ChapterId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Chapters");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.ChatCitation", b =>
                {
                    b.Property<int>("ChatCitationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChatCitationId"));

                    b.Property<int>("ChatHistoryId")
                        .HasColumnType("int");

                    b.Property<int>("DocumentChunkId")
                        .HasColumnType("int");

                    b.Property<int>("RetrievalRank")
                        .HasColumnType("int");

                    b.Property<double>("SimilarityScore")
                        .HasColumnType("float");

                    b.HasKey("ChatCitationId");

                    b.HasIndex("ChatHistoryId");

                    b.HasIndex("DocumentChunkId");

                    b.ToTable("ChatCitations");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.ChatHistory", b =>
                {
                    b.Property<int>("ChatHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChatHistoryId"));

                    b.Property<int>("ChatSessionId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LatencyMs")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("TokenCount")
                        .HasColumnType("int");

                    b.HasKey("ChatHistoryId");

                    b.HasIndex("ChatSessionId");

                    b.ToTable("ChatHistories");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.ChatSession", b =>
                {
                    b.Property<int>("ChatSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChatSessionId"));

                    b.Property<int>("AiModelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmbeddingModelId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastActivityAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("TopK")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ChatSessionId");

                    b.HasIndex("AiModelId");

                    b.HasIndex("EmbeddingModelId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("UserId");

                    b.ToTable("ChatSessions");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.ChunkingStrategy", b =>
                {
                    b.Property<int>("ChunkingStrategyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChunkingStrategyId"));

                    b.Property<int>("ChunkOverlap")
                        .HasColumnType("int");

                    b.Property<int>("ChunkSize")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("StrategyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StrategyType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ChunkingStrategyId");

                    b.ToTable("ChunkingStrategies");

                    b.HasData(
                        new
                        {
                            ChunkingStrategyId = 1,
                            ChunkOverlap = 64,
                            ChunkSize = 512,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Split text into fixed-size token windows with overlap",
                            IsActive = true,
                            IsDefault = true,
                            StrategyName = "Fixed Size 512",
                            StrategyType = "FixedSize"
                        },
                        new
                        {
                            ChunkingStrategyId = 2,
                            ChunkOverlap = 0,
                            ChunkSize = 1024,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Split text at paragraph boundaries (double newlines)",
                            IsActive = true,
                            IsDefault = false,
                            StrategyName = "Paragraph Split",
                            StrategyType = "Paragraph"
                        },
                        new
                        {
                            ChunkingStrategyId = 3,
                            ChunkOverlap = 32,
                            ChunkSize = 256,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Split text at sentence boundaries with sliding window",
                            IsActive = true,
                            IsDefault = false,
                            StrategyName = "Sentence Split",
                            StrategyType = "Sentence"
                        },
                        new
                        {
                            ChunkingStrategyId = 4,
                            ChunkOverlap = 64,
                            ChunkSize = 512,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Recursively split using hierarchy: paragraph → sentence → word",
                            IsActive = true,
                            IsDefault = false,
                            StrategyName = "Recursive Character",
                            StrategyType = "Recursive"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Document", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentId"));

                    b.Property<int>("ChapterId")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("IndexedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("StoragePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("TotalChunks")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("int");

                    b.HasKey("DocumentId");

                    b.HasIndex("ChapterId");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.DocumentChunk", b =>
                {
                    b.Property<int>("DocumentChunkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentChunkId"));

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("int");

                    b.Property<string>("ChunkText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<string>("EmbeddingJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmbeddingModelId")
                        .HasColumnType("int");

                    b.Property<int>("TokenCount")
                        .HasColumnType("int");

                    b.Property<int>("VectorDimension")
                        .HasColumnType("int");

                    b.HasKey("DocumentChunkId");

                    b.HasIndex("EmbeddingModelId");

                    b.HasIndex("DocumentId", "ChunkIndex");

                    b.ToTable("DocumentChunks");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.DocumentIndex", b =>
                {
                    b.Property<int>("DocumentIndexId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentIndexId"));

                    b.Property<int>("ChunkingStrategyId")
                        .HasColumnType("int");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<int>("EmbeddingModelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("IndexedAt")
                        .HasColumnType("datetime2");

                    b.Property<double?>("IndexingDurationSeconds")
                        .HasColumnType("float");

                    b.Property<int>("TotalChunks")
                        .HasColumnType("int");

                    b.Property<int>("VectorDimension")
                        .HasColumnType("int");

                    b.HasKey("DocumentIndexId");

                    b.HasIndex("ChunkingStrategyId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("EmbeddingModelId");

                    b.ToTable("DocumentIndexes");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.EmbeddingModel", b =>
                {
                    b.Property<int>("EmbeddingModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmbeddingModelId"));

                    b.Property<string>("ApiEndpoint")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("VectorDimension")
                        .HasColumnType("int");

                    b.HasKey("EmbeddingModelId");

                    b.HasIndex("ModelName")
                        .IsUnique();

                    b.ToTable("EmbeddingModels");

                    b.HasData(
                        new
                        {
                            EmbeddingModelId = 1,
                            ApiEndpoint = "https://generativelanguage.googleapis.com/v1beta",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Google Gemini text-embedding-004 (768 dims)",
                            IsActive = true,
                            IsDefault = true,
                            ModelName = "text-embedding-004",
                            Provider = "Gemini",
                            VectorDimension = 768
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Experiment", b =>
                {
                    b.Property<int>("ExperimentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExperimentId"));

                    b.Property<int>("AiModelId")
                        .HasColumnType("int");

                    b.Property<int>("ChunkingStrategyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("EmbeddingModelId")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ExperimentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("TopK")
                        .HasColumnType("int");

                    b.HasKey("ExperimentId");

                    b.HasIndex("AiModelId");

                    b.HasIndex("ChunkingStrategyId");

                    b.HasIndex("EmbeddingModelId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Experiments");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("SubjectCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("SubjectId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.SubjectTeacher", b =>
                {
                    b.Property<int>("SubjectTeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectTeacherId"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SubjectTeacherId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("UserId", "SubjectId")
                        .IsUnique();

                    b.ToTable("SubjectTeachers");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.TestSet", b =>
                {
                    b.Property<int>("TestSetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestSetId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExpectedAnswer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExperimentId")
                        .HasColumnType("int");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tags")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("TestSetId");

                    b.HasIndex("ExperimentId");

                    b.ToTable("TestSets");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Student");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@rag-lms.edu.vn",
                            FullName = "System Administrator",
                            IsActive = true,
                            PasswordHash = "240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Entities.BenchmarkResult", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Experiment", "Experiment")
                        .WithMany("BenchmarkResults")
                        .HasForeignKey("ExperimentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entities.TestSet", "TestSet")
                        .WithMany("BenchmarkResults")
                        .HasForeignKey("TestSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experiment");

                    b.Navigation("TestSet");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Chapter", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Subject", "Subject")
                        .WithMany("Chapters")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.ChatCitation", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.ChatHistory", "ChatHistory")
                        .WithMany("Citations")
                        .HasForeignKey("ChatHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entities.DocumentChunk", "DocumentChunk")
                        .WithMany("Citations")
                        .HasForeignKey("DocumentChunkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChatHistory");

                    b.Navigation("DocumentChunk");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.ChatHistory", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.ChatSession", "ChatSession")
                        .WithMany("ChatHistories")
                        .HasForeignKey("ChatSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatSession");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.ChatSession", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.AiModel", "AiModel")
                        .WithMany("ChatSessions")
                        .HasForeignKey("AiModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entities.EmbeddingModel", "EmbeddingModel")
                        .WithMany()
                        .HasForeignKey("EmbeddingModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entities.Subject", "Subject")
                        .WithMany("ChatSessions")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entities.User", "User")
                        .WithMany("ChatSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiModel");

                    b.Navigation("EmbeddingModel");

                    b.Navigation("Subject");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Document", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Chapter", "Chapter")
                        .WithMany("Documents")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entities.User", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chapter");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.DocumentChunk", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Document", "Document")
                        .WithMany("DocumentChunks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entities.EmbeddingModel", "EmbeddingModel")
                        .WithMany("DocumentChunks")
                        .HasForeignKey("EmbeddingModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("EmbeddingModel");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.DocumentIndex", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.ChunkingStrategy", "ChunkingStrategy")
                        .WithMany("DocumentIndexes")
                        .HasForeignKey("ChunkingStrategyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entities.Document", "Document")
                        .WithMany("DocumentIndexes")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entities.EmbeddingModel", "EmbeddingModel")
                        .WithMany("DocumentIndexes")
                        .HasForeignKey("EmbeddingModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChunkingStrategy");

                    b.Navigation("Document");

                    b.Navigation("EmbeddingModel");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Experiment", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.AiModel", "AiModel")
                        .WithMany("Experiments")
                        .HasForeignKey("AiModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entities.ChunkingStrategy", "ChunkingStrategy")
                        .WithMany("Experiments")
                        .HasForeignKey("ChunkingStrategyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entities.EmbeddingModel", "EmbeddingModel")
                        .WithMany()
                        .HasForeignKey("EmbeddingModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entities.Subject", "Subject")
                        .WithMany("Experiments")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AiModel");

                    b.Navigation("ChunkingStrategy");

                    b.Navigation("EmbeddingModel");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.SubjectTeacher", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Subject", "Subject")
                        .WithMany("SubjectTeachers")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entities.User", "User")
                        .WithMany("SubjectTeachers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.TestSet", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Experiment", "Experiment")
                        .WithMany("TestSets")
                        .HasForeignKey("ExperimentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experiment");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.AiModel", b =>
                {
                    b.Navigation("ChatSessions");

                    b.Navigation("Experiments");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Chapter", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.ChatHistory", b =>
                {
                    b.Navigation("Citations");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.ChatSession", b =>
                {
                    b.Navigation("ChatHistories");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.ChunkingStrategy", b =>
                {
                    b.Navigation("DocumentIndexes");

                    b.Navigation("Experiments");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Document", b =>
                {
                    b.Navigation("DocumentChunks");

                    b.Navigation("DocumentIndexes");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.DocumentChunk", b =>
                {
                    b.Navigation("Citations");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.EmbeddingModel", b =>
                {
                    b.Navigation("DocumentChunks");

                    b.Navigation("DocumentIndexes");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Experiment", b =>
                {
                    b.Navigation("BenchmarkResults");

                    b.Navigation("TestSets");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Subject", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("ChatSessions");

                    b.Navigation("Experiments");

                    b.Navigation("SubjectTeachers");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.TestSet", b =>
                {
                    b.Navigation("BenchmarkResults");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.User", b =>
                {
                    b.Navigation("ChatSessions");

                    b.Navigation("SubjectTeachers");
                });
#pragma warning restore 612, 618
        }
    }
}
